const Router = require("express").Router()
const {getCertificatedUsers,getGuidesList,getSingleGuide,getGuidesCount} = require("../controllers/website/guides")
const {createToken,isAllowed,verifyToken} = require("../middlewares/auth")
const {postAuthorizeUser,getUserProfile,postSignOutUser} = require("../controllers/website/login")
const {getDownloadCertificate,postCreateApplication,getListOfUsersApplication,getSingleUserApplication,postAnswerApplication} = require("../controllers/website/applications")
const {upload} = require("../middlewares/multerUpload")
const {checkJoiCreateApplication} = require("../middlewares/joiValidator")
const {getLangsAndRegs} = require("../controllers/website/staticData")
const {getOrganizationsList,getRegionsList} = require("../controllers/website/organization")
const {getActiveQuarters} = require("../controllers/admin/quarter")
const {getTestTopics,getTestQuestions,postCreateTestAnswer,checkTestAttempts,getTestResults,checkTestForQuarter} = require("../controllers/website/test")

Router.get("/langsregs",getLangsAndRegs)
Router.get("/regions", getRegionsList)
Router.get("/organizations", getOrganizationsList)
Router.get("/quarters", getActiveQuarters)
Router.get("/volunteers",getCertificatedUsers)
Router.get("/volunteers/count",getGuidesCount)
Router.get("/volunteers/single",getSingleGuide)
Router.post("/login",createToken,postAuthorizeUser)
Router.get("/me",verifyToken,isAllowed(["user","admin","super"]),getUserProfile)
Router.get("/download/:id",getDownloadCertificate)
Router.get("/test/topics",getTestTopics)
Router.get("/test/questions/:test_topic_id",getTestQuestions)
Router.post("/test/answer",postCreateTestAnswer)
Router.get("/test/attempts", checkTestAttempts)
Router.get("/test/results", getTestResults)
Router.get("/test/check-quarter", checkTestForQuarter)
Router.post("/logout",verifyToken,isAllowed(["user","admin","super"]),postSignOutUser)
//Router.post("/applications/create",upload(["./files/private/applications",{fieldname:"badge_img",path:"./files/public/images"}]).any(),postCreateApplication)
Router.post("/applications/create",upload(["./public"]).single("image"),postCreateApplication)
Router.get("/applications",getListOfUsersApplication)
Router.get("/applications/:id",getSingleUserApplication)
// Router.post("/applications/payment/:id",verifyToken,isAllowed(["user","super"]),upload(["./files/private/applications"]).single("file"),postAnswerApplication)
//,verifyToken,isAllowed(["user","super"])
module.exports = Router

